=== aleks4ay/alex_masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://javaops.ru"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Groups">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="Group"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>
    </xs:element>

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="email"/>
                <xs:element type="xs:string" name="fullName"/>
                <xs:element name="groups" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="group" type="xs:IDREF"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="City" type="cityType"/>
    <xs:element name="Project" type="projectType"/>
    <xs:element name="Group" type="groupType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="projectType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="groupType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
                <xs:attribute type="xs:IDREF" name="project" use="required"/>
                <xs:attribute type="groupConditionType" name="condition" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>


    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="groupConditionType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="registering"/>
            <xs:enumeration value="current"/>
            <xs:enumeration value="finished"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== aleks4ay/alex_masterjava/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">
    <Users>
        <User flag="active" city="kiv">
            <email>gmail@gmail.com</email>
            <fullName>Full Name</fullName>
            <groups>
                <group>tj01</group>
                <group>mj01</group>
            </groups>
        </User>
        <User flag="superuser" city="spb">
            <email>admin@javaops.ru</email>
            <fullName>Admin</fullName>
        </User>
        <User flag="deleted" city="spb">
            <email>mail@yandex.ru</email>
            <fullName>Deleted</fullName>
        </User>
    </Users>
    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>
    <Projects>
        <Project id="tj">topjava</Project>
        <Project id="mj">masterjava</Project>
    </Projects>
    <Groups>
        <Group id="tj01" project="tj" condition="finished">topjava-01</Group>
        <Group id="tj02" project="tj" condition="current">topjava-02</Group>
        <Group id="mj01" project="mj" condition="current">masterjava-01</Group>
        <Group id="mj02" project="mj" condition="registering">masterjava-02</Group>
    </Groups>
</Payload>
